<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ExceedanceFilterApp\ExceedanceFilterApp.csproj" />
	<ProjectReference Include="..\PhaseFilterApp\PhaseFilterApp.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>PC24FDAP</AssemblyName>
    <Description>CP24 FDAP Analyzer</Description>
  </PropertyGroup>

</Project>
